CREATE TABLE IF NOT EXISTS company(
id BIGSERIAL PRIMARY KEY ,
name VARCHAR (128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS employee(
id BIGSERIAL PRIMARY KEY ,
first_name VARCHAR (128) NOT NULL ,
second_name VARCHAR (128) NOT NULL ,
age INTEGER NOT NULL ,
company_id BIGINT REFERENCES company(id)
);

CREATE TABLE IF NOT EXISTS address(
id BIGSERIAL PRIMARY KEY ,
city VARCHAR (128) NOT NULL,
street VARCHAR (128) NOT NULL,
employee_id BIGINT REFERENCES employee(id)
);